### ISSUE TITLE
`skip-odf-reports` traits error with `dsi_studio_autotrack`

### ISSUE THREAD

**Issue by smeisler** [PennLINC/qsirecon#104]
## Additional details

- QSIRecon version: unstable (8 days ago)
- Singularity version: Apptainer 1.1.7

### What were you trying to do?
Run `dsi_studio_autotrack` but skip ODF reports due to HPC graphics rendering oddities
### What actually happened?
```
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/cli/workflow.py", line 139, in build_workflow
    retval["workflow"] = init_qsirecon_wf()
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/workflows/base.py", line 54, in init_qsirecon_wf
    single_subject_wf = init_single_subject_recon_wf(subject_id=subject_id)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/workflows/base.py", line 222, in init_single_subject_recon_wf
    dwi_recon_wfs[dwi_file] = init_dwi_recon_workflow(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/workflows/recon/build_workflow.py", line 58, in init_dwi_recon_workflow
    new_node = workflow_from_spec(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/workflows/recon/build_workflow.py", line 213, in workflow_from_spec
    return init_dsi_studio_autotrack_wf(**kwargs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/workflows/recon/dsi_studio.py", line 344, in init_dsi_studio_autotrack_wf
    AutoTrack(num_threads=omp_nthreads, **params), name="actual_trk", n_procs=omp_nthreads
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 629, in __init__
    super(CommandLine, self).__init__(**inputs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
    self.inputs.trait_set(**inputs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/has_traits.py", line 1520, in trait_set
    setattr(self, name, value)
traits.trait_errors.TraitError: Cannot set the undefined 'plot_reports' attribute of a '_AutoTrackInputSpec' object.
```
## Reproducing the bug
```
apptainer run \
-e \
--containall \
-B /om2 \
${qsirecon_img} \
$bids \
$out participant \
-w $work \
--fs-license-file ${license} \
--recon-spec ${recon_spec} \
--skip-odf-reports \
--notrack \
--mem-mb 63000 --nthreads 16 --omp-nthreads 8
```

**Comment by smeisler** [comment]
Yup that did it!
