### ISSUE TITLE
Plot peaks doesn't work for NODDI in multishell_scalarfest

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsirecon#130]
## Summary

Piggybacking on #122, outputting the peaks mosaic crashes when attempting to do so, specifically for `fit_noddi_gm`.

## Additional details

- QSIRecon version: 0.23.1
- Singularity version: 1.3.2-1.el7

## Reproducing the bug

```
apptainer run -\
-containall --writable-tmpfs \
-B $PWD/derivatives/qsiprep_0.22.1/qsiprep:/input \
-B $PWD/derivatives/qsirecon:/output \
-B /tmp:/tmp \
-B /groups/adamraikes/license.txt:/license.txt \
$RECON /input /output participant \
--participant_label 001 \
-w /tmp  \
--nthreads 8 --omp-nthreads 8 --fs-license-file /license.txt --recon-spec multishell_scalarfest --input-type qsiprep
```

## Crash log
```
Node: qsirecon_0_23_wf.sub-001_multishell_scalarfest.sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf.fit_noddi_gm.plot_peaks
Working directory: /tmp/qsirecon_0_23_wf/sub-001_multishell_scalarfest/sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf/fit_noddi_gm/plot_peaks

Node inputs:

args = <undefined>
background_image = <undefined>
directions_file = <undefined>
environ = {}
fib_file = <undefined>
mask_file = <undefined>
mif_file = <undefined>
odf_file = <undefined>
odf_report = odfs_mosaic.png
odf_rois = <undefined>
peak_report = peaks_mosaic.png
peaks_only = False
subtract_iso = False

Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node plot_peaks.

Cmdline:
	recon_plot --background_image /tmp/qsirecon_0_23_wf/sub-001_multishell_scalarfest/sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf/fit_noddi_gm/recon_noddi/study/subject/AMICO/NODDI/fit_NDI.nii.gz --fib /tmp/qsirecon_0_23_wf/sub-001_multishell_scalarfest/sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf/fit_noddi_gm/convert_to_fibgz/fit_NDI.fib --mask_file /tmp/qsirecon_0_23_wf/sub-001_multishell_scalarfest/sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_dwi_specific_anat_wf/resample_mask/sub-001_desc-brain_mask_trans.nii.gz --odfs_image odfs_mosaic.png --peaks_image peaks_mosaic.png
Stdout:
	241016-14:33:30,904 nipype.interface INFO:
		 converting /tmp/qsirecon_0_23_wf/sub-001_multishell_scalarfest/sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf/fit_noddi_gm/convert_to_fibgz/fit_NDI.fib to plot ODF/peaks
Stderr:
	Killed
Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 'peak_report' trait of a _ReconPeaksReportOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/tmp/qsirecon_0_23_wf/sub-001_multishell_scalarfest/sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf/fit_noddi_gm/plot_peaks/peaks_mosaic.png' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 400, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/tmp/qsirecon_0_23_wf/sub-001_multishell_scalarfest/sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf/fit_noddi_gm/plot_peaks/peaks_mosaic.png' for output 'peak_report' of a CLIReconPeaksReport interface
```

**Comment by smeisler** [comment]
Hi @araikes,

```
Stderr:
	Killed
```
Indicates an out-of-memory error. How much memory did you give the job?

**Comment by araikes** [comment]
Yeah, I hadn't had a chance to update, but I agree. I think when I ran the job the first time with 24 cores and 5Gb per core, then multiple concurrent tasks caused the crash. When I threw 94 cores at it, I didn't have an issue.

**Comment by smeisler** [comment]
Huh, that seems like it should have been sufficient memory to begin with, but since this appears to be a resource error and not a qsiprep error per se, I am going to close this for now. But please reopen if this becomes persistent after we finish our next big round of changes!
