### ISSUE TITLE
calc_connectivity failed to run in dsi_studio_gqi pipeline

### ISSUE THREAD

**Issue by samuelholly** [PennLINC/qsirecon#145]
## Summary
`calc_connectivity` failed to run in `dsi_studio_gqi` pipeline

## Additional details

- QSIRecon version: unstable (as of 5th Nov 2024)
- Docker version: 4.10.1
- Singularity version: NA

### What were you trying to do?
Run the `dsi_studio_gqi` pipeline

### What did you expect to happen?
Succesfull finish

### What actually happened?
I'm getting the following errors:
```
Node calc_connectivity failed to run on host 2d8c3803d7db.
241105-07:41:07,319 nipype.workflow ERROR:
         Saving crash info to /out/sub-019/log/20241105-073553_66f06269-c5d3-45bd-ab05-cade161659b3/crash-20241105-074107-root-calc_connectivity-905173fd-d418-49ea-a7a4-45b67fff648e.txt
Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node calc_connectivity.

Traceback:
        Traceback (most recent call last):
          File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 397, in run
            runtime = self._run_interface(runtime)
          File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/interfaces/dsi_studio.py", line 409, in _run_interface
            DSIStudioConnectivityMatrix(
        TypeError: qsirecon.interfaces.dsi_studio.DSIStudioConnectivityMatrix() got multiple values for keyword argument 'atlas_name'


241105-07:41:07,323 nipype.workflow INFO:
         [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 21.01/21.01, Free processors: 8/8.
241105-07:41:09,317 nipype.workflow INFO:
         ***********************************
241105-07:41:09,317 nipype.workflow ERROR:
         could not run node: qsirecon_0_23_wf.sub-019_dsistudio_pipeline.sub_019_acq_ep2ddtib3000tra64p2_dir_AP_space_T1w_desc_preproc_recon_wf.streamline_connectivity.calc_connectivity
241105-07:41:09,317 nipype.workflow INFO:
         crashfile: /out/sub-019/log/20241105-073553_66f06269-c5d3-45bd-ab05-cade161659b3/crash-20241105-074107-root-calc_connectivity-905173fd-d418-49ea-a7a4-45b67fff648e.txt
241105-07:41:09,317 nipype.workflow INFO:
         ***********************************
241105-07:41:09,333 nipype.workflow CRITICAL:
         QSIRecon failed: Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node calc_connectivity.

Traceback:
        Traceback (most recent call last):
          File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 397, in run
            runtime = self._run_interface(runtime)
          File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/interfaces/dsi_studio.py", line 409, in _run_interface
            DSIStudioConnectivityMatrix(
        TypeError: qsirecon.interfaces.dsi_studio.DSIStudioConnectivityMatrix() got multiple values for keyword argument 'atlas_name'
```
## Reproducing the bug
I ran the following command:
```
docker run -ti --rm \
-v H:\qsiprep_out\qsiprep:/data \
-v H:\qsirecon_out:/out \
-v W:\license.txt:/opt/freesurfer/license.txt \
pennlinc/qsirecon:unstable /data /out participant \
--fs-license-file /opt/freesurfer/license.txt \
--output-resolution 2 \
--recon-spec dsi_studio_gqi \
-vv \
--n_cpus 8 \
--resource-monitor \
--write-graph \
--notrack \
--participant-label 019 \
--atlases 4S156Parcels\
```
I also attached the crash file. Thanks for your help.
[crash-20241105-074107-root-calc_connectivity-905173fd-d418-49ea-a7a4-45b67fff648e.txt](https://github.com/user-attachments/files/17629311/crash-20241105-074107-root-calc_connectivity-905173fd-d418-49ea-a7a4-45b67fff648e.txt)

**Comment by mattcieslak** [comment]
I reproduced this bug and there is a fix in #151

**Comment by samuelholly** [comment]
Thank you. I'm still very new to GitHub, should I wait for the code to be included in the main branch to test it?

**Comment by samuelholly** [comment]
Great, thank you. I tried it. There is still an error (see below), but the processing seems to have finished anyway. I can open the results in DSI studio.

The error:

```
[MultiProc] Running 1 tasks, and 0 jobs ready. Free memory (GB): 20.81/21.01, Free processors: 1/8.
                     Currently running:
                       * qsirecon_0_23_wf.sub-019_dsistudio_pipeline.sub_019_acq_ep2ddtib3000tra64p2_dir_AP_space_T1w_desc_preproc_recon_wf.dsistudio_gqi.gqi_recon
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/opt/conda/envs/qsiprep/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/opt/conda/envs/qsiprep/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/opt/conda/envs/qsiprep/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 722, in _run_command
    result = self._interface.run(cwd=outdir, ignore_exception=True)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 400, in run
    outputs = self.aggregate_outputs(runtime)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 429, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/interfaces/dsi_studio.py", line 210, in _list_outputs
    config.loggers.interface.info("current dir", os.getcwd())
Message: 'current dir'
Arguments: ('/tmp/work/qsirecon_0_23_wf/sub-019_dsistudio_pipeline/sub_019_acq_ep2ddtib3000tra64p2_dir_AP_space_T1w_desc_preproc_recon_wf/dsistudio_gqi/gqi_recon',)
```
