### ISSUE TITLE
HSVS 5TT datasink fails with longitudinal freesurfer

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsirecon#162]
Testing #151. Ran into the following

```
Node: qsirecon_0_0_wf.sub-011_mrtrix_multishell_msmt_hsvs.recon_anatomical_wf_0.ds_fs_5tt_hsvs
Working directory: /xdisk/adamraikes/PD_allo/derivatives/qsirecon_unstable/sessionwise/reports_session/scratch/qsirecon_0_0_wf/sub-011_mrtrix_multishell_msmt_hsvs/recon_anatomical_wf_0/ds_fs_5tt_hsvs

Node inputs:

acquisition = <undefined>
atlas = <undefined>
base_directory = /xdisk/adamraikes/PD_allo/derivatives/qsirecon_unstable/sessionwise/reports_session
bundle = <undefined>
bundles = <undefined>
ceagent = <undefined>
check_hdr = True
chunk = <undefined>
cohort = <undefined>
compress = [True]
data_dtype = <undefined>
datatype = <undefined>
den = <undefined>
desc = <undefined>
direction = <undefined>
dismiss_entities = ['desc']
echo = <undefined>
extension = <undefined>
flip = <undefined>
fmap = <undefined>
from = <undefined>
hemi = <undefined>
in_file = ['/xdisk/adamraikes/PD_allo/derivatives/qsirecon_unstable/sessionwise/reports_session/scratch/qsirecon_0_0_wf/sub-011_mrtrix_multishell_msmt_hsvs/recon_anatomical_wf_0/create_5tt_hsvs/sub-011_ses-01.long_5tt.mif']
inv = <undefined>
label = <undefined>
meta_dict = <undefined>
modality = <undefined>
mode = <undefined>
model = <undefined>
mt = <undefined>
nucleus = <undefined>
param = <undefined>
part = <undefined>
proc = <undefined>
reconstruction = <undefined>
recording = <undefined>
res = <undefined>
roi = <undefined>
run = <undefined>
sample = <undefined>
scans = <undefined>
seg = hsvs
session = <undefined>
source_file = ['/xdisk/adamraikes/PD_allo/derivatives/qsiprep_unstable/sessionwise/sub-011/ses-01/anat/sub-011_ses-01_space-ACPC_desc-preproc_T1w.nii.gz']
space = fsnative
staining = <undefined>
subject = <undefined>
subset = <undefined>
suffix = probseg
task = <undefined>
to = <undefined>
tracer = <undefined>
tracksys = <undefined>
volume = <undefined>

Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ds_fs_5tt_hsvs.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/niworkflows/interfaces/bids.py", line 632, in _run_interface
	    raise ValueError(f"Could not build path with entities {out_entities}.")
	ValueError: Could not build path with entities {'subject': '011', 'session': '01', 'space': 'fsnative', 'suffix': 'probseg', 'datatype': 'anat', 'extension': 'long_5tt.mif.gz', 'seg': 'hsvs'}.
```

**Comment by tsalo** [comment]
I think the extension should just be `.mif.gz`, not `long_5tt.mif.gz`. We can probably fix this by hardcoding the extension in the DerivativesDataSink.
